[dotfiles]
"~/.config/git" = { mode = "track" }
"~/.config/karabiner/karabiner.json" = { mode = "track" }
"~/.config/mise" = { mode = "track" }
"~/.config/starship.toml" = { mode = "track" }
"~/.zshrc/alias" = { block = '''
alias reload='exec "$SHELL" -l'

alias c="clear"
alias cpt='pbcopy'
alias cpd='pwd | pbcopy'

alias m='mise'
alias mu='mise use'
alias mr='mise run'
alias mi='mise install'
alias md='mise dotfiles'

alias mb='mise bootstrap'
alias mbp='mise bootstrap packages'

alias lx='~/.local/bin/lazymux'
''' }
"~/.zshrc/editors" = { block = '''
export EDITOR="hx"
export VISUAL="codium"
''' }
"~/.zshrc/prompt-gap" = { block = '''
_prompt_should_add_gap=0
_prompt_add_gap() {
  (( _prompt_should_add_gap )) && print
  _prompt_should_add_gap=1
}
autoload -Uz add-zsh-hook
add-zsh-hook precmd _prompt_add_gap
''' }
"~/.zshrc/starship" = { block = 'eval "$(starship init zsh)"' }
"~/Library/Application Support/VSCodium/product.json" = { mode = "track" }
