[formatting]
align_entries = true

[schema]
path = "https://mise.jdx.dev/schema/mise.json"
include = [
  "**/mise/config.toml",
  "**/mise/conf.d/*.toml",
  "**/mise.toml",
  "**/.mise.toml",
  "**/mise.*.toml",        # mise.local.toml, mise.dev.toml, etc.
]
