[formatting]
align_entries = true

[[rule]]
include = [
  "**/mise/config.toml",
  "**/mise/conf.d/*.toml",
  "**/mise.toml",
  "**/.mise.toml",
  "**/mise.*.toml",        # mise.local.toml, mise.dev.toml, etc.
]

[rule.schema]
url = "https://mise.jdx.dev/schema/mise.json"
